version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: projectnewtest_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile.dev
    command: yarn start:dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: projectnewtest_db
      DB_USER: postgres
      DB_PASS: postgres

  admin-panel:
    build:
      context: .
      dockerfile: apps/admin-panel/Dockerfile.dev
    command: yarn dev
    volumes:
      # 1) monta tu código fuente para que puedas hacer hot-reload
      - .:/usr/src/app

      # 2) monta un volumen anónimo en node_modules para preservar los binarios Linux
      - /usr/src/app/node_modules
    ports:
      - '3001:3001'
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3000

volumes:
  db_data:
